### PR TITLE
feat(docs): add information about mapping page URL

### PR DESCRIPTION
**Pull request by bytrangle**
## Description

I added more information for the prop `mapPageUrlFn` of component Render.

### CODE REVIEW

**Comment by 9gustin** [comment]
@bytrangle  A question about this functionallity, how did you see this case in notion? are like a "Mention to a page"? or how did you build a link to "**/ID**" 🤔

**Comment by bytrangle** [comment]
Let's say I have this paragraph:

> We recently wrote about all the *reasons why your company website needs a blog*.

The part inside the asterisks is supposed to link to page `notion.so/why-your-company-website-needs-a-blog-ID`.

Users can select the part inside the asterisks, then click **Add link** from the popup menu, or hit `Cmd + K`, then enter the url above.

Alternatively, they can type: "We recently wrote about all the", then hit `@` to mention and select the destination page.

Both CMD + K and Mention produce the same markup.

Does that make sense?

**Comment by 9gustin** [comment]
Yes but, the code validate if url[0] be equal to '/' instead of notion url. Anyway i dont have tested it yet, im going to test in dev-example. 

Thanks for it ✨

**Review by 9gustin — APPROVED** [review]

**Comment by 9gustin** [comment]
Forget it, now i have tested it locally and works nice. again, thankssss ❤️

**Pull request merged**
